server:
  port: 8080
spring:
  application:
    name: auth-server
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    env:
      enabled: true
    logfile:
      enabled: true
    loggers:
      enabled: true
    mappings:
      enabled: true
    configprops:
      enabled: true
    scheduledtasks:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
logging.level.org.springframework.security: DEBUG
